import { describe, expect, test } from "bun:test";
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { parseFrontmatter } from "../cli/src/generator";
import { repoRoot, tempDir } from "./helpers";

function markdownFiles(relativeDir: string): string[] {
  const dir = join(repoRoot, relativeDir);
  return readdirSync(dir)
    .filter((name) => name.endsWith(".md"))
    .sort();
}

function packedFiles(): Set<string> {
  const output = execFileSync(
    "npm",
    [
      "pack",
      "--dry-run",
      "--json",
      "--ignore-scripts",
      "--cache",
      tempDir("monkeybars-npm-cache-"),
      "--pack-destination",
      tempDir("monkeybars-pack-")
    ],
    { cwd: repoRoot, encoding: "utf8" }
  );
  const [pack] = JSON.parse(output) as Array<{ files: Array<{ path: string }> }>;
  return new Set(pack.files.map((file) => file.path));
}

describe("surface guardrails", () => {
  test("every source command has generated OpenCode and skill adapters", () => {
    for (const file of markdownFiles("workflow-src/commands")) {
      const { meta } = parseFrontmatter(join(repoRoot, "workflow-src", "commands", file));
      expect(readFileSync(join(repoRoot, "plugins", "monkeybars", "commands", `${meta.name}.md`), "utf8")).toContain(
        "Generated by MonkeyBars"
      );
      expect(
        readFileSync(join(repoRoot, "plugins", "monkeybars", "skills", meta.name, "SKILL.md"), "utf8")
      ).toContain("Generated by MonkeyBars");
    }
  });

  test("every included template exists and is copied into the plugin", () => {
    const copiedTemplates = new Set(markdownFiles("plugins/monkeybars/templates"));
    for (const file of markdownFiles("workflow-src/templates")) {
      expect(copiedTemplates.has(file)).toBe(true);
    }

    for (const file of markdownFiles("workflow-src/commands")) {
      const { meta } = parseFrontmatter(join(repoRoot, "workflow-src", "commands", file));
      const templates = meta.include_templates
        ?.split(",")
        .map((name) => name.trim().replace(/\.md$/, ""))
        .filter(Boolean) ?? [];
      for (const template of templates) {
        expect(copiedTemplates.has(`${template}.md`)).toBe(true);
      }
    }
  });

  test("npm pack includes shipped workflow assets", () => {
    const files = packedFiles();

    for (const file of [
      "dist/index.js",
      ".agents/plugins/marketplace.json",
      "plugins/monkeybars/.codex-plugin/plugin.json",
      "plugins/monkeybars/commands/map-codebase.md",
      "plugins/monkeybars/hooks/shared/monkeybars-workflow-context.js",
      "plugins/monkeybars/hooks/opencode/monkeybars-workflow.js",
      "plugins/monkeybars/scripts/install-opencode-commands.sh",
      "plugins/monkeybars/skills/map-codebase/SKILL.md",
      "plugins/monkeybars/templates/current-stack.md"
    ]) {
      expect(files.has(file)).toBe(true);
    }
  });
});
