import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
  readFileSync
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export interface FrontmatterResult {
  meta: Record<string, string>;
  body: string;
}

export interface GenerateOptions {
  root?: string;
  pluginOutput?: string;
}

export interface GeneratedCheckResult {
  ok: boolean;
  differences: string[];
}

interface Paths {
  root: string;
  source: string;
  plugin: string;
  commandSource: string;
  templateSource: string;
  hookSource: string;
}

const GENERATED_MARKER = ".monkeybars-generated.json";

function moduleDirectory(): string {
  return dirname(fileURLToPath(import.meta.url));
}

function defaultRoot(): string {
  const fromModule = moduleDirectory();
  const candidates = [resolve(fromModule, "..", ".."), resolve(fromModule, ".."), process.cwd()];
  for (const candidate of candidates) {
    if (existsSync(join(candidate, "workflow-src")) && existsSync(join(candidate, "plugins", "monkeybars"))) {
      return candidate;
    }
  }
  return resolve(fromModule, "..", "..");
}

function paths(rootOption?: string): Paths {
  const root = resolve(rootOption ?? defaultRoot());
  const source = join(root, "workflow-src");
  return {
    root,
    source,
    plugin: join(root, "plugins", "monkeybars"),
    commandSource: join(source, "commands"),
    templateSource: join(source, "templates"),
    hookSource: join(source, "hooks")
  };
}

function pathsWithOutput(options: GenerateOptions): Paths {
  const allPaths = paths(options.root);
  return options.pluginOutput ? { ...allPaths, plugin: resolve(options.pluginOutput) } : allPaths;
}

function sortedMarkdownFiles(directory: string): string[] {
  return readdirSync(directory)
    .filter((name) => name.endsWith(".md"))
    .sort()
    .map((name) => join(directory, name));
}

function resetDir(path: string): void {
  if (existsSync(path)) {
    rmSync(path, { recursive: true, force: true });
  }
  mkdirSync(path, { recursive: true });
}

export function parseFrontmatter(path: string): FrontmatterResult {
  const text = readFileSync(path, "utf8");
  if (!text.startsWith("---\n")) {
    throw new Error(`${path} is missing YAML-style frontmatter`);
  }

  const end = text.indexOf("---\n", 4);
  if (end === -1) {
    throw new Error(`${path} is missing closing frontmatter delimiter`);
  }

  const rawMeta = text.slice(4, end);
  const body = text.slice(end + 4).replace(/^\s+/, "");
  const meta: Record<string, string> = {};

  for (const line of rawMeta.split(/\r?\n/)) {
    if (!line.trim()) continue;
    const match = line.match(/^([A-Za-z][A-Za-z0-9_-]*)\s*:\s*(.*)$/);
    if (!match) {
      throw new Error(`Invalid frontmatter line in ${path}: ${line}`);
    }
    const key = match[1].trim();
    if (Object.hasOwn(meta, key)) {
      throw new Error(`Duplicate frontmatter key in ${path}: ${key}`);
    }
    meta[key] = parseFrontmatterValue(match[2].trim(), path, line);
  }

  if (!meta.name || !meta.description) {
    throw new Error(`${path} must define name and description`);
  }

  return { meta, body };
}

function parseFrontmatterValue(value: string, path: string, line: string): string {
  if (!value) return "";

  if (value.startsWith('"')) {
    try {
      const parsed = JSON.parse(value);
      if (typeof parsed !== "string") {
        throw new Error("frontmatter value is not a string");
      }
      return parsed;
    } catch (error) {
      throw new Error(
        `Invalid quoted frontmatter value in ${path}: ${line} (${
          error instanceof Error ? error.message : String(error)
        })`
      );
    }
  }

  if (value.startsWith("'")) {
    if (!value.endsWith("'") || value.length === 1) {
      throw new Error(`Invalid quoted frontmatter value in ${path}: ${line}`);
    }
    return value.slice(1, -1).replace(/''/g, "'");
  }

  return value;
}

function renderFrontmatterValue(value: string): string {
  if (/^(?!true$|false$|null$)[A-Za-z0-9][A-Za-z0-9 ./_-]*$/i.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}

function generatedHeader(source?: string): string {
  const suffix = source ? ` from ${source}` : "";
  return `<!-- Generated by MonkeyBars${suffix}. Edit workflow-src/ instead. -->`;
}

export function renderSkill(meta: Record<string, string>, body: string): string {
  return [
    "---",
    `name: ${renderFrontmatterValue(meta.name)}`,
    `description: ${renderFrontmatterValue(meta.description)}`,
    "disable-model-invocation: true",
    "---",
    "",
    generatedHeader(),
    "",
    body
  ].join("\n");
}

export function renderOpenCodeCommand(meta: Record<string, string>, body: string): string {
  const lines = ["---", `description: ${renderFrontmatterValue(meta.description)}`];
  if (meta.opencode_agent) {
    lines.push(`agent: ${renderFrontmatterValue(meta.opencode_agent)}`);
  }
  lines.push("---", "", generatedHeader(), "", body);
  return lines.join("\n");
}

function includedTemplateNames(meta: Record<string, string>): string[] {
  const value = meta.include_templates?.trim();
  if (!value) return [];
  return value
    .split(",")
    .map((name) => name.trim().replace(/\.md$/, ""))
    .filter(Boolean);
}

function markdownFenceFor(text: string): string {
  const longest = text.match(/`+/g)?.reduce((max, match) => Math.max(max, match.length), 0) ?? 0;
  return "`".repeat(Math.max(3, longest + 1));
}

function appendIncludedTemplates(body: string, names: string[], allPaths: Paths): string {
  if (names.length === 0) return body;

  const sections = names.map((name) => {
    const templatePath = join(allPaths.templateSource, `${name}.md`);
    if (!existsSync(templatePath)) {
      throw new Error(`Included template does not exist: ${name}`);
    }
    const template = readFileSync(templatePath, "utf8").trimEnd();
    const fence = markdownFenceFor(template);
    return [`### \`templates/${name}.md\``, "", `${fence}markdown`, template, fence].join("\n");
  });

  return [
    body.trimEnd(),
    "",
    "## Included Templates",
    "",
    "Use these bundled templates when creating or updating project-local workflow files.",
    "",
    sections.join("\n\n")
  ].join("\n");
}

function copyTemplates(allPaths: Paths): void {
  const target = join(allPaths.plugin, "templates");
  resetDir(target);
  const files: string[] = [];
  for (const template of sortedMarkdownFiles(allPaths.templateSource)) {
    const name = template.split(/[\\/]/).at(-1) ?? "";
    copyFileSync(template, join(target, name));
    files.push(name);
  }
  writeMarker(target, { type: "templates", files });
}

function copyDirectory(source: string, target: string): void {
  resetDir(target);
  if (!existsSync(source)) {
    writeMarker(target, { type: "directory", files: [] });
    return;
  }
  const files: string[] = [];

  const copyRecursive = (sourcePath: string): void => {
    for (const name of readdirSync(sourcePath)) {
      const sourceEntry = join(sourcePath, name);
      const relativePath = relative(source, sourceEntry);
      const destination = join(target, relativePath);
      const stat = statSync(sourceEntry);
      if (stat.isDirectory()) {
        mkdirSync(destination, { recursive: true });
        copyRecursive(sourceEntry);
        continue;
      }
      mkdirSync(join(destination, ".."), { recursive: true });
      copyFileSync(sourceEntry, destination);
      chmodSync(destination, stat.mode);
      files.push(relative(target, destination));
    }
  };

  copyRecursive(source);
  writeMarker(target, { type: "directory", files: files.sort() });
}

function writeMarker(directory: string, data: Record<string, unknown>): void {
  writeFileSync(
    join(directory, GENERATED_MARKER),
    `${JSON.stringify({ generatedBy: "monkeybars", ...data }, null, 2)}\n`
  );
}

export function generateAdapters(options: GenerateOptions = {}): string {
  const allPaths = pathsWithOutput(options);
  const skillsDir = join(allPaths.plugin, "skills");
  const commandsDir = join(allPaths.plugin, "commands");
  resetDir(skillsDir);
  resetDir(commandsDir);
  const skillNames: string[] = [];
  const commandFiles: string[] = [];

  for (const sourceFile of sortedMarkdownFiles(allPaths.commandSource)) {
    const { meta, body } = parseFrontmatter(sourceFile);
    const name = meta.name;
    const renderedBody = appendIncludedTemplates(body, includedTemplateNames(meta), allPaths);

    const skillDir = join(skillsDir, name);
    mkdirSync(skillDir, { recursive: true });
    writeFileSync(join(skillDir, "SKILL.md"), renderSkill(meta, renderedBody));
    skillNames.push(name);

    const commandFile = `${name}.md`;
    writeFileSync(join(commandsDir, commandFile), renderOpenCodeCommand(meta, renderedBody));
    commandFiles.push(commandFile);
  }
  writeMarker(skillsDir, { type: "skills", directories: skillNames.sort() });
  writeMarker(commandsDir, { type: "commands", files: commandFiles.sort() });

  copyTemplates(allPaths);
  copyDirectory(allPaths.hookSource, join(allPaths.plugin, "hooks"));
  return allPaths.plugin;
}

function collectFiles(directory: string): string[] {
  if (!existsSync(directory)) return [];
  const files: string[] = [];
  const walk = (current: string): void => {
    for (const name of readdirSync(current).sort()) {
      const path = join(current, name);
      const stat = statSync(path);
      if (stat.isDirectory()) {
        walk(path);
      } else if (stat.isFile()) {
        files.push(relative(directory, path));
      }
    }
  };
  walk(directory);
  return files;
}

function compareGeneratedDirectory(expected: string, actual: string, label: string): string[] {
  const differences: string[] = [];
  const expectedFiles = collectFiles(expected);
  const actualFiles = collectFiles(actual);
  const allFiles = [...new Set([...expectedFiles, ...actualFiles])].sort();

  for (const file of allFiles) {
    const expectedPath = join(expected, file);
    const actualPath = join(actual, file);
    if (!existsSync(expectedPath)) {
      differences.push(`${label}/${file} exists but is no longer generated`);
      continue;
    }
    if (!existsSync(actualPath)) {
      differences.push(`${label}/${file} is missing`);
      continue;
    }
    if (readFileSync(expectedPath, "utf8") !== readFileSync(actualPath, "utf8")) {
      differences.push(`${label}/${file} differs`);
    }
  }

  return differences;
}

export function checkGeneratedAdapters(options: GenerateOptions = {}): GeneratedCheckResult {
  const root = resolve(options.root ?? defaultRoot());
  const tempRoot = mkdtempSync(join(tmpdir(), "monkeybars-generate-"));
  const expectedPlugin = join(tempRoot, "plugins", "monkeybars");

  try {
    generateAdapters({ root, pluginOutput: expectedPlugin });
    const actualPlugin = join(root, "plugins", "monkeybars");
    const generatedDirs = ["commands", "skills", "templates", "hooks"];
    const differences = generatedDirs.flatMap((directory) =>
      compareGeneratedDirectory(join(expectedPlugin, directory), join(actualPlugin, directory), `plugins/monkeybars/${directory}`)
    );
    return { ok: differences.length === 0, differences };
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
}
